### ISSUE TITLE
About SFA implementation

### ISSUE THREAD

**Issue by evil-lov** [plemeri/UACANet#1]
Hello, Is it convenient to share the SFA code in this article? Suddenly found that the original author deleted this code

**Comment by plemeri** [comment]
Hello, thanks for asking. Actually I didn't use any source code from SFA in the first place. I added the config file for it just for the evaluation code. You can find result images of SFA, UNet and UNet++ from https://github.com/DengPingFan/PraNet and move them into the results directory and just use my evaluation code to reproduce.

**Comment by evil-lov** [comment]
Hello, there is no result images of SFA, UNET and unet++ in this link. Do you have any? Can you share one with me through email? Thank you very much.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "plemeri/UACANet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月19日(星期一) 上午8:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [plemeri/UACANet] About SFA implementation (#1)





 
Hello, thanks for asking. Actually I didn't use any source code from SFA in the first place. I added the config file for it just for the evaluation code. You can find result images of SFA, UNet and UNet++ from https://github.com/DengPingFan/PraNet and move them into the results directory and just use my evaluation code to reproduce.

**Comment by evil-lov** [comment]
Hello, I found result images. Sorry to disturb you.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "plemeri/UACANet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月19日(星期一) 上午8:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [plemeri/UACANet] About SFA implementation (#1)





 
Hello, thanks for asking. Actually I didn't use any source code from SFA in the first place. I added the config file for it just for the evaluation code. You can find result images of SFA, UNet and UNet++ from https://github.com/DengPingFan/PraNet and move them into the results directory and just use my evaluation code to reproduce.

**Comment by plemeri** [comment]
No need to apologize. Good luck!
