### ISSUE TITLE
Results on ETIS-LaribPolypDB dataset

### ISSUE THREAD

**Issue by enric1994** [plemeri/UACANet#10]
I tried to reproduce your results following your README instructions. I used the default `UACANet-L` config with a batch size of 8 instead of 32. 

The mDICE I get on 3 runs on ETIS-LaribPolypDB is 0.52/0.56/0.53 while in the paper you get 0.76
Can you verify this? Why is the lower batch size affecting only this dataset?

**Comment by plemeri** [comment]
Hi, thank you for your comment.
Images in the ETIS dataset are more high resolution than other datasets, including training dataset.
I think that's the reason why it shows lower performance with the small batch size.

**Comment by WangZhi-wz** [comment]
> 

Could you please tell me how to get the ETIS dataset

**Comment by plemeri** [comment]
See #12
