### ISSUE TITLE
Clarification on pretrained weights

### ISSUE THREAD

**Issue by enric1994** [plemeri/UACANet#11]
When `pretrained: True` the pretrained weights in `data/backbone_ckpt/res2net50_v1b_26w_4s-3cf99910.pth` are used. 
Where do these weights come from? Are they pretrained on colon images by you, or they are pretrained just on ImageNet?

**Comment by plemeri** [comment]
Hi, thanks again for your interest.
As I mentioned at the end of the readme, it is brought from the PraNet repository.
Also, it is pre-trained with ImageNet 1K dataset.
