### ISSUE TITLE
Could you please tell me how to get the CVC-300，CVC-ColonDB，ETIS dataset

### ISSUE THREAD

**Issue by WangZhi-wz** [plemeri/UACANet#12]
Could you please tell me how to get the CVC-300，CVC-ColonDB，ETIS dataset

**Comment by plemeri** [comment]
You can download them from [here](https://postechackr-my.sharepoint.com/:u:/g/personal/taehoon1018_postech_ac_kr/EdqOjDpjDNZCnyFUd68FmzcBu9aN-vUX3HE_H1VM_9vorQ?e=xWg4Cw). Or you can just find them from [PraNet](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjb7-y435D6AhV-4TgGHb3ND2wQFnoECBwQAQ&url=https%3A%2F%2Fgithub.com%2FDengPingFan%2FPraNet&usg=AOvVaw1nmhPHes0Wh4rduymOsZUF)
