### ISSUE TITLE
Why is my eval result 0 except for Sm, meanEm, mae, maxEm?

### ISSUE THREAD

**Issue by louan1998** [plemeri/UACANet#15]
I followed the steps in the readme to train and test UACANat-L, why in the end all datasets evaluated the result was 0
![QQ图片20231122171727](https://github.com/plemeri/UACANet/assets/52094628/9c76b7b2-ba2c-48ba-9a63-0a408c004207)

**Comment by Zoe-TAN** [comment]
Hi. Have u solved this problem? Same problem here.

**Comment by louan1998** [comment]
> Hi. Have u solved this problem? Same problem here.

There was something wrong with the test set given by this project. I used the test set from another [project](https://github.com/DengPingFan/Polyp-PVT), The data sets and the division of the data sets are the same for both projects and got the results.
