### ISSUE TITLE
About this Baseline model

### ISSUE THREAD

**Issue by avyer** [plemeri/UACANet#3]
What is the structure of this Baseline model? What kind of connection does it have with UACANet?

**Comment by plemeri** [comment]
Thank you for your comments about our project.

The baseline model is just a simplified version of our model. The overall structure is identical, but the modules are more simplified. (e.g., [UACA](https://github.com/plemeri/UACANet/blob/e968a447824b19932e503190d6b9e75b7c225833/lib/modules/attention_module.py#L112-L170) -> [simple attention](https://github.com/plemeri/UACANet/blob/e968a447824b19932e503190d6b9e75b7c225833/lib/modules/attention_module.py#L31-L51)). Maybe I need to remove them since people might get confused.

**Comment by avyer** [comment]
Thank you for your answer. I have another question. I read your article and saw that the order of the graph structure of PAA_e is 1x3 Conv, 3x1 Conv, 3x3 Conv, PAA. But now when I look at the code, I found that the PAA_e module first performed 1x1 Conv, then 1x3 Conv, 3x1 Conv, PAA, and 3x3 Conv. Why is the order of the code inconsistent with the order of the graphics drawn in the article? So which one shall we prevail? Or do I understand it incorrectly? Thank you very much for your answer. code show as below:

class PAA_kernel(nn.Module):
    def __init__(self, in_channel, out_channel, receptive_size=3):
        super(PAA_kernel, self).__init__()
        self.conv0 = conv(in_channel, out_channel, 1)
        self.conv1 = conv(out_channel, out_channel, kernel_size=(1, receptive_size))
        self.conv2 = conv(out_channel, out_channel, kernel_size=(receptive_size, 1))
        self.conv3 = conv(out_channel, out_channel, 3, dilation=receptive_size)
        self.Hattn = self_attn(out_channel, mode='h')
        self.Wattn = self_attn(out_channel, mode='w')

    def forward(self, x):
        x = self.conv0(x)
        x = self.conv1(x)
        x = self.conv2(x)

        Hx = self.Hattn(x)
        Wx = self.Wattn(x)

        x = self.conv3(Hx + Wx)
        return x

**Comment by plemeri** [comment]
Well, it's obviously my mistake that I missed that part in the paper. Thank you for letting me know about this problem!
I'll post some comment about this. Until then, please follow our implementation for your research.
Moreover, PAA module is a small modification of [RFB](https://arxiv.org/pdf/1711.07767.pdf) which is not our major contribution. You may want to find other works for multi-scale context modules like [ASPP](https://arxiv.org/abs/1802.02611) if you're interested in.

**Comment by avyer** [comment]
Well, thank you very much for your answer!
