### ISSUE TITLE
Some questions about Axial-attention 

### ISSUE THREAD

**Issue by Liqq1** [plemeri/UACANet#8]
Hi~I have some questions about Axial-attention 
Why [there](https://github.com/AngeLouCN/CaraNet/blob/2664929e03e1fa8a0763de149b002a573027d547/lib/self_attention.py#L37) is no premute operation before view in mode h?
```
# for mode h
projected_query = self.query_conv(x).premute(0, 1, 3, 2).view(*view).permute(0, 2, 1)
```
I think premute is necessary. Although the shape of those values are correct to calculate，it has a very different meaning for mode h comparing to mode w. Without premute, the projected_query can't actually collect the columns to the dimension with size Hight
For example:
![image](https://user-images.githubusercontent.com/54054113/155883374-e2bf013f-8de7-42ac-9383-9403a50d74b4.png)
For mode W, the way of reshape is correct.
![image](https://user-images.githubusercontent.com/54054113/155883385-904718f1-a77f-439b-9205-491d53ef25fc.png)
Without permute for mode H, it is obviously not what we want:
![image](https://user-images.githubusercontent.com/54054113/155883392-deaccc18-3753-4f3c-bc29-e1a61ae99191.png)
With permute for mode H,[0, 5, 10, 15] is the column of a.:
![image](https://user-images.githubusercontent.com/54054113/155883400-e5432720-a09d-4b7d-a4e7-60a6cb3be5a1.png)

**Comment by plemeri** [comment]
I think you are right. Thank you for letting me know. I'll keep in mind this in my future works.

**Comment by Liqq1** [comment]
> 

Okay！And  thanks for your great code work, this is a very clear template！

**Comment by Asthestarsfalll** [comment]
Any intention to re-train all model in this repo? @plemeri

**Comment by plemeri** [comment]
I'm not planning to since this isn't our main contribution, but thanks for letting me know that the authors of CaraNet seems to be using our code without any citation. I really feel bad about it.

**Comment by SimonServant** [comment]
It seems as if they don't even use the axial attention module they mention in the paper, as they apply a residual connection in the end and multiply the output of the axial attention module with zero. At least this is what my unknowing eyes see in their github repository.

**Comment by Liqq1** [comment]
Hi，did you delete your comment？I can only see it in the email notification，not in the githun issue



发自我的iPhone


------------------ Original ------------------
From: Simon Diener ***@***.***&gt;
Date: Tue,Jul 26,2022 3:35 AM
To: plemeri/UACANet ***@***.***&gt;
Cc: machine no learning ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [plemeri/UACANet] Some questions about Axial-attention  (Issue#8)





 
It seems as if they don't even use the axial attention module they mention in the paper, as they apply a residual connection in the end and multiply the output of the axial attention module with zero. At least this is what my unknowing eyes see in their github repository.

**Comment by SimonServant** [comment]
Hello, yes i had sadly misunderstood the usage of the attention module for CaraNet. I initially thought, that they implemented the code similar, but ended up not using the axial attention, misinterpreting the inital gamma value of the self attention layer and mixing up the implementaton with the reverse attention module. It is indeed correct, that the axial attention is used by CaraNet, unreferenced in the published paper. However i think they reference that fact in the official repository. 

I am sry for disturbing you with that comment and wanted to delete it, once i realized my initial assumption to be wrong.

**Comment by plemeri** [comment]
I just noticed that the author of [CaraNet](https://github.com/AngeLouCN/CaraNet/) updated their [readme](https://github.com/AngeLouCN/CaraNet/commit/e8895258282a1b82808fbe73f2de07f1e2565a2d).
